routes/web.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix'=>'eloquent','as'=>'eloquent.'],function(){
    Route::get('clients','EloquentClientsController@index')->name('clients.list');
});
Route::group(['prefix'=>'admin','as'=>'admin.'],function(){
    Route::get('client','ClientsController@create');
    Route::post('client','ClientsController@store')->name('client.store');
});
Route::group(['prefix'=>'','as'=>'site.'],function(){
    Route::get('client','SiteClientsController@create');
    Route::post('client','SiteClientsController@store')->name('client.store');
});

/*Route::get('/minharota',function(){
    return view('helloworld');
});
Route::get('minharota/rota1',function(){
    return view('helloworld1');
});
Route::get('client',function(){
    return view('client');
});
Route::post('client',function(Request $request){
    return $request->get('value');
})->name('client.store');

Route::get('client/{id}/{name?}',function($id,$name = "Fulano"){
    return view('client-name')->with('id',$id)->with('name',$name)->with('conteudo','teste');
});
Route::get('if-for',function(){
    return view('if-for');
});*/

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'name','address'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClientsController extends Controller
{
    public function create(){
        return view('admin.client.client');
    }
    public function store(Request $request){
        return $request->get('value');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EloquentClientsController.php
<?php

namespace App\Http\Controllers;
use App\Client;
use Illuminate\Http\Request;

class EloquentClientsController extends Controller
{   
    public function index(){

        $clients = Client::all();

        return view('eloquent.index',[
            'clients'=>$clients
        ]);
        
    }
    public function create(){
        return view('admin.client.client');
    }
    public function store(Request $request){
        return $request->get('value');
    }
}

app/Http/Controllers/SiteClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiteClientsController extends Controller
{
    public function create(){
        return view('site.client');
    }
    public function store(Request $request){
        return $request->get('value');
    }
}

resources/views/admin/client/client.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <h1>Site Client</h1>
    <form method="post" action="{{route('admin.client.store')}}">
        <input type="hidden" name="_token" value="{{csrf_token()}}">
        <input type="text" name="value">
        <button type="submit">Enviar</button>
    </form>
</body>
</html>

resources/views/client-name.blade.php
<p>Nome: {{$name}}</p>
<p>ID: {{$id}}</p>
<p>{{isset($conteudo)? $conteudo : "Variável não exite"}}</p>
<p>{{$conteudo or 'Variavel não existe'}}</p>

resources/views/eloquent/index.blade.php
<h1>Listagem de Clientes </h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach($clients as $client)
        <tr>
            <td>{{$client->id}}</td>
            <td>{{$client->name}}</td>
            <td>{{$client->address}}</td>
        </tr>

        @endforeach
      
    </tbody>

</table>

resources/views/helloworld.blade.php
<?php
    echo "Hello World";
?>

resources/views/helloworld1.blade.php
<?php
    echo "Hello World 1";
?>

resources/views/if-for.blade.php
<?php 
$num = 20;
?>

{{"Exemplo de estrutura condicional"}}

@if($num < 20)
    <p>Numero é menor que 20</p>
@elseif($num ==20)
    <p>Numero é igual a 20</p>
@else 
    <p>Numero é maior que 20</p>
@endif


{{"Exemplo de estrutura de repetição"}}

@for($i = 0; $i < 20;$i++)
    <p>Valor: {{$i}}</p> 
@endfor

<?php 
$k = 0;
?>
{{"WHILE"}}

@while($k <20)
    <p>Valor: {{$k}}</p> 
    <?php $k++?>
@endwhile

<?php 
$array =[1,2,3,4,5];
?>
{{"FOREACH"}}

@foreach($array as $value)
    <p>Chave{{$loop->index}}, Valor: {{$value}}</p>
@endforeach
<?php 
$array =[];
?>
@forelse($array as $value)
    <p>Chave{{$loop->index}}, Valor: {{$value}}</p>
@empty
    <p>Nenhum elemento Encontrado</p>
@endforelse

resources/views/site/client.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>

    <form method="post" action="{{route('site.client.store')}}">
        <input type="hidden" name="_token" value="{{csrf_token()}}">
        <input type="text" name="value">
        <button type="submit">Enviar</button>
    </form>
</body>
</html>